services:
  - type: web
    name: fagni-backend
    env: python
    region: frankfurt
    branch: main
    rootDir: .
    buildCommand: |
      pip install -r requirements.txt
      python manage.py migrate
      python manage.py collectstatic --noinput || true
    startCommand: gunicorn fagni.wsgi:application --bind 0.0.0.0:$PORT
    autoDeploy: true
    plan: free
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "*"
      - key: CORS_ALLOW_ALL_ORIGINS
        value: "True"
