services:
  - type: web
    name: fagni-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt && python manage.py migrate && python manage.py collectstatic --noinput || true
    startCommand: gunicorn fagni_backend.wsgi:application --bind 0.0.0.0:$PORT   # (ou fagni_backend.wsgi si tu es revenu au module)
    healthCheckPath: /api/health/
